extends: '@zakodium/eslint-config/typescript-react'
rules:
  'import/default': off
  'import/no-unresolved': off
  '@typescript-eslint/no-explicit-any': off
  no-restricted-imports:
    - error
    - name: lodash
      message: "Use a deep import instead, like for example 'lodash/get'"
    - name: '@simbathesailor/use-what-changed'
      message: 'Remove use-what-changed before committing the code'
  no-restricted-syntax:
    - error
    - selector: "CallExpression[callee.name='forwardRef']"
      message: 'forwardRef() must not be invoked. use forwardRefWithAs instead.'
parserOptions:
  sourceType: module
