name: E2E tests

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Build test application
        run: npm run build
      - name: Run E2E tests on ${{ matrix.browser }}
        run: npm run test-e2e
        env:
          BROWSER: ${{ matrix.browser }}
