name: nmrium gh-pages tag publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          npm ci
          npm i -g gh-pages
      - name: Build
        run: |
          rm src/demo/samples.json
          mv src/demo/empty.json src/demo/samples.json
          npm run build
      - name: Remove spectra
        run: rm -rf build/data
      - name: Push to gh-pages
        run: |
          git config user.email luc@patiny.com
          git config user.name "Luc Patiny"
          git remote set-url origin "https://lpatiny:${{ secrets.ACCESS_NMRIUM }}@github.com/zakodium/nmrium.org.git"
          VERSION=${GITHUB_REF//*\/}
          gh-pages --dest $VERSION -d build --dotfiles
